<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="jakarta.tags.core" prefix="c" %>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Saved Items - StudentOS</title><link rel="stylesheet" href="/css/main.css?v=saved-items-1"><link rel="icon" type="image/png" href="/favicon.png"></head>
<body><div class="app-container">
    <aside class="sidebar"><div class="sidebar-logo"><span class="logo-mark">S</span> Student OS</div><div class="nav-group"><div class="nav-title">Workspace</div><a href="/dashboard" class="nav-link">Overview</a><a href="/goals" class="nav-link">Goals</a><a href="/schedule" class="nav-link">Schedule</a></div><div class="nav-group"><div class="nav-title">Community</div><a href="/skills/discover" class="nav-link">Discover talent</a><a href="/skills" class="nav-link">My skills</a><a href="/collaborations" class="nav-link">Collaborations</a><a href="/saved" class="nav-link active">Saved items</a><a href="/messages" class="nav-link">Messages<c:if test="${unreadMessageCount gt 0}"><span class="notification-badge"><c:out value="${unreadMessageCount}"/></span></c:if></a><a href="/notifications" class="nav-link">Notifications<c:if test="${unreadNotificationCount gt 0}"><span class="notification-badge"><c:out value="${unreadNotificationCount}"/></span></c:if></a><a href="/profile" class="nav-link">My profile</a></div><div class="nav-group"><div class="nav-title">Opportunities</div><a href="/freelance" class="nav-link">Freelance jobs</a><a href="/freelance/services" class="nav-link">Services</a></div><div class="sidebar-footer"><a href="/auth/logout" class="nav-link nav-link-danger">Log out</a></div></aside>
    <main class="main-content"><header class="page-header"><div><p class="eyebrow">Private workspace</p><h1 class="page-title">Saved items</h1><p class="page-subtitle">Keep useful student profiles, skills, service offers, and opportunities ready for when you want to return.</p></div><a class="btn btn-primary" href="/skills/discover">Discover students</a></header>
        <c:if test="${param.removed eq '1'}"><div class="alert alert-success">The item was removed from your private saved list.</div></c:if><c:if test="${param.removed eq '0'}"><div class="alert alert-error">That item could not be removed.</div></c:if>
        <nav class="saved-filter-bar" aria-label="Saved item filters"><a class="<c:if test='${empty savedType}'>active</c:if>" href="/saved">All</a><a class="<c:if test='${savedType eq "PROFILE"}'>active</c:if>" href="/saved?type=PROFILE">Profiles</a><a class="<c:if test='${savedType eq "SKILL"}'>active</c:if>" href="/saved?type=SKILL">Skills</a><a class="<c:if test='${savedType eq "SERVICE"}'>active</c:if>" href="/saved?type=SERVICE">Services</a><a class="<c:if test='${savedType eq "JOB"}'>active</c:if>" href="/saved?type=JOB">Opportunities</a></nav>
        <section class="saved-item-grid"><c:choose><c:when test="${not empty savedItems}"><c:forEach var="item" items="${savedItems}"><article class="card saved-item-card"><div class="card-header"><div><p class="section-kicker"><c:out value="${item.typeLabel}"/></p><h2 class="card-title"><c:out value="${item.title}"/></h2></div><span class="badge badge-todo">Saved</span></div><p class="saved-item-detail"><c:out value="${item.detail}"/></p><div class="owner-actions"><a class="btn btn-secondary" href="<c:out value='${item.targetUrl}'/>">Open item</a><form method="post" action="/saved/remove"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}'/>"><input type="hidden" name="id" value="<c:out value='${item.id}'/>"><button class="text-action text-action-danger" type="submit">Remove</button></form></div></article></c:forEach></c:when><c:otherwise><article class="card saved-empty"><p class="section-kicker">Start a shortlist</p><h2>Nothing saved yet</h2><p>When you find a classmate, skill, service offer, or job worth returning to, save it here. Your saved list is private to your StudentOS account.</p><div class="owner-actions"><a class="btn btn-primary" href="/skills/discover">Discover talent</a><a class="btn btn-secondary" href="/freelance">Explore jobs</a></div></article></c:otherwise></c:choose></section>
        <footer class="mkv-footer">© 2026 MKV Team</footer></main></div><script src="/js/mobile-nav.js?v=mobile-nav-phone-6" defer></script></body></html>
