-- StudentOS intentionally ships without default user accounts or passwords.
--
-- Create development users through the registration flow, which exercises the
-- same verification and password hashing behavior as production. Never add
-- shared credentials, API keys, connection strings, or production personal
-- data to this repository.
--
-- For a local administrator account, use a unique strong password and create
-- it through a private database-administration process. Do not reuse example
-- credentials across environments.
