<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="jakarta.tags.core" prefix="c" %>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>My Skills - Student OS</title><link rel="stylesheet" href="/css/main.css"></head>
<body><div class="app-container">
<aside class="sidebar"><div class="sidebar-logo">STUDENT OS</div>
<div class="nav-group"><div class="nav-title">My Life</div><a href="/dashboard" class="nav-link">Overview</a><a href="/goals" class="nav-link">Goals</a><a href="/schedule" class="nav-link">Schedule</a></div>
<div class="nav-group"><div class="nav-title">Skills</div><a href="/skills/discover" class="nav-link">Discover</a><a href="/skills" class="nav-link" style="background-color:var(--border-color)">My Skills</a></div>
<div class="nav-group"><div class="nav-title">Work</div><a href="/freelance" class="nav-link">Freelance Jobs</a><a href="/freelance/services" class="nav-link">Services</a></div>
<div style="margin-top:auto"><a href="/auth/logout" class="nav-link" style="color:var(--danger)">Logout</a></div></aside>
<main class="main-content"><header class="page-header"><div><h1 class="page-title">My Skills</h1><p class="page-subtitle">Manage what you know and what you want to learn.</p></div><button class="btn btn-primary" type="button" onclick="document.getElementById('skillModal').style.display='flex'">+ Add Skill</button></header>
<section class="grid-2"><c:choose><c:when test="${empty mySkills}"><div class="card">No skills yet. Add a skill to start building your profile.</div></c:when><c:otherwise><c:forEach var="skill" items="${mySkills}"><article class="card"><div class="card-header"><div class="card-title"><c:out value="${skill.skillName}"/></div><span class="badge badge-todo"><c:out value="${skill.type}"/></span></div><p style="color:var(--text-secondary)">Level: <c:out value="${skill.skillLevel}"/></p></article></c:forEach></c:otherwise></c:choose></section>
</main></div>
<div id="skillModal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);align-items:center;justify-content:center"><div style="background:var(--bg-primary);padding:32px;border-radius:12px;width:100%;max-width:400px"><h2>Add Skill</h2><form action="/skills/add" method="post"><div class="form-group"><label class="form-label" for="skillName">Skill Name</label><input id="skillName" class="form-control" name="skillName" required></div><div class="form-group"><label class="form-label" for="skillLevel">Skill Level</label><select id="skillLevel" class="form-control" name="skillLevel"><option value="BEGINNER">Beginner</option><option value="INTERMEDIATE">Intermediate</option><option value="ADVANCED">Advanced</option><option value="EXPERT">Expert</option></select></div><div class="form-group"><label class="form-label" for="skillType">I want to</label><select id="skillType" class="form-control" name="type"><option value="TEACH">Teach this skill</option><option value="LEARN">Learn this skill</option></select></div><button class="btn btn-primary" type="submit">Save Skill</button></form></div></div>
</body></html>
