<%-- Design direction: calm editorial control room with strong operational traceability. --%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.util.*" %>
<%@ page import="com.studentos.util.HtmlUtil" %>
<%
List<Map<String,Object>> entries = (List<Map<String,Object>>) request.getAttribute("auditEntries");
if (entries == null) entries = new ArrayList<>();
String auditQuery = (String) request.getAttribute("auditQuery"); if (auditQuery == null) auditQuery = "";
String auditAction = (String) request.getAttribute("auditAction");
Integer auditTotal = (Integer) request.getAttribute("auditTotal"); if (auditTotal == null) auditTotal = entries.size();
Integer auditPage = (Integer) request.getAttribute("auditPage"); if (auditPage == null) auditPage = 1;
Integer auditPages = (Integer) request.getAttribute("auditPages"); if (auditPages == null) auditPages = 1;
%>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Moderation audit - StudentOS</title><link rel="stylesheet" href="/css/main.css?v=admin-ui-20260822"><link rel="icon" type="image/png" href="/favicon.png"></head>
<body><div class="admin-shell"><aside class="admin-rail"><div class="admin-brand">StudentOS <span>Admin</span></div><nav aria-label="Administrator navigation"><a href="/admin">Dashboard</a><a href="/admin/users">Users</a><a href="/admin/content">Content</a><a href="/admin/messages">Messages</a><a href="/admin/reports">Reports</a><a href="/admin/audit" class="active">Audit log</a><a href="/dashboard">Back to App</a></nav><div class="admin-rail-footer"><a href="/auth/logout">Logout</a></div></aside>
<main class="admin-main"><header class="admin-header"><div><p class="eyebrow">Accountability</p><h1>Moderation audit log</h1><p>The latest protected administration and moderation actions, including review reasons where they were provided.</p></div><span class="admin-status"><%=auditTotal%> matching event<%=auditTotal == 1 ? "" : "s"%></span></header>
<form class="admin-filter-bar" method="get" action="/admin/audit"><div class="admin-filter-field admin-filter-search"><label class="visually-hidden" for="auditSearch">Search audit history</label><input id="auditSearch" name="q" value="<%=HtmlUtil.escapeHtml(auditQuery)%>" maxlength="100" placeholder="Search admin, action, target, or reason"></div><div class="admin-filter-field"><label class="visually-hidden" for="auditAction">Filter by action</label><input id="auditAction" name="action" value="<%=HtmlUtil.escapeHtml(auditAction)%>" maxlength="80" placeholder="Exact action, for example REPORT_RESOLVED"></div><button class="btn btn-primary" type="submit">Apply filters</button><a class="btn btn-secondary" href="/admin/audit">Clear</a></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>When</th><th>Administrator</th><th>Action</th><th>Target</th><th>Reason</th></tr></thead><tbody><% if (entries.isEmpty()) { %><tr><td colspan="5">No audit entries match these controls.</td></tr><% } %><% for (Map<String,Object> entry : entries) { %><tr><td><%=entry.get("created_at")%></td><td><strong><%=HtmlUtil.escapeHtml(entry.get("admin_email"))%></strong></td><td><%=HtmlUtil.escapeHtml(entry.get("action"))%></td><td><%=HtmlUtil.escapeHtml(entry.get("target_type"))%> #<%=entry.get("target_id")%></td><td><%=HtmlUtil.escapeHtml(entry.get("reason"))%></td></tr><% } %></tbody></table></div><% if (auditPages > 1) { %><form class="admin-pagination" method="get" action="/admin/audit"><input type="hidden" name="q" value="<%=HtmlUtil.escapeHtml(auditQuery)%>"><input type="hidden" name="action" value="<%=HtmlUtil.escapeHtml(auditAction)%>"><button class="btn btn-secondary" type="submit" name="page" value="<%=auditPage - 1%>" <%=auditPage <= 1 ? "disabled" : ""%>>Previous</button><span>Page <strong><%=auditPage%></strong> of <strong><%=auditPages%></strong></span><button class="btn btn-secondary" type="submit" name="page" value="<%=auditPage + 1%>" <%=auditPage >= auditPages ? "disabled" : ""%>>Next</button></form><% } %><footer class="mkv-footer">© 2026 MKV Team</footer></main></div><script src="/js/admin-nav.js?v=20260822"></script></body></html>
