<%-- Design direction: calm editorial control room with unmistakable moderation status and careful destructive actions. --%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.util.*,com.studentos.util.HtmlUtil" %>
<%
    List<Map<String,Object>> skills = (List<Map<String,Object>>) request.getAttribute("skills");
    List<Map<String,Object>> jobs = (List<Map<String,Object>>) request.getAttribute("jobs");
    List<Map<String,Object>> services = (List<Map<String,Object>>) request.getAttribute("services");
    if (skills == null) skills = new ArrayList<>(); if (jobs == null) jobs = new ArrayList<>(); if (services == null) services = new ArrayList<>();
    String msg = request.getParameter("msg"); String csrfToken = (String) request.getAttribute("csrfToken");
%>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Content — Admin — StudentOS</title><link rel="stylesheet" href="/css/main.css?v=admin-ui-20260822"><link rel="icon" type="image/png" href="/favicon.png"></head>
<body><div class="admin-shell"><aside class="admin-rail"><div class="admin-rail-logo">StudentOS <span>Admin</span></div><nav class="admin-nav" aria-label="Administrator navigation"><a href="/admin">Dashboard</a><a href="/admin/users">Users</a><a href="/admin/content" class="active">Content</a><a href="/admin/messages">Messages</a><a href="/admin/reports">Reports</a><a href="/admin/audit">Audit log</a><a href="/dashboard">Back to App</a></nav><div class="admin-rail-footer"><a href="/auth/logout">Logout</a></div></aside>
<main class="admin-main"><header class="admin-header"><div><p class="eyebrow">Content safety</p><h1>Content moderation</h1><p>Review skills, jobs, and services with clear visibility status and a fully recorded moderation path.</p></div><span class="admin-status"><%=skills.size()+jobs.size()+services.size()%> items listed</span></header>
<% if (msg != null) { %><div class="toast">Updated: <%=HtmlUtil.escapeHtml(msg.replace("_"," "))%></div><% } %>

<h2 class="section-title">Skills · <%=skills.size()%></h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>ID</th><th>Owner</th><th>Skill</th><th>Level</th><th>Type</th><th>Visibility</th><th>Moderation actions</th></tr></thead><tbody>
<% for (Map<String,Object> r : skills) { boolean hidden = "HIDDEN".equals(r.get("moderation_status")); %><tr><td><%=r.get("id")%></td><td><%=HtmlUtil.escapeHtml(r.get("email"))%></td><td><strong><%=HtmlUtil.escapeHtml(r.get("skill_name"))%></strong></td><td><%=HtmlUtil.escapeHtml(r.get("skill_level"))%></td><td><%=HtmlUtil.escapeHtml(r.get("type"))%></td><td><span class="badge <%=hidden ? "badge-banned" : "badge-active"%>"><%=HtmlUtil.escapeHtml(r.get("moderation_status"))%></span></td><td><div class="action-row"><form method="post" action="/admin/content/<%=hidden ? "restore" : "hide"%>"><input type="hidden" name="targetType" value="SKILL"><input type="hidden" name="targetId" value="<%=r.get("id")%>"><input type="hidden" name="reason" value="Manual moderation review"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><button class="btn-sm <%=hidden ? "btn-unban" : "btn-ban"%>"><%=hidden ? "Restore" : "Hide"%></button></form><form method="post" action="/admin/content/delete-skill"><input type="hidden" name="id" value="<%=r.get("id")%>"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><button class="btn-sm btn-delete" onclick="return confirm('Delete this skill?')">Delete</button></form></div></td></tr><% } %>
</tbody></table></div>

<h2 class="section-title">Freelance jobs · <%=jobs.size()%></h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>ID</th><th>Owner</th><th>Title</th><th>Status</th><th>Visibility</th><th>Moderation actions</th></tr></thead><tbody>
<% for (Map<String,Object> r : jobs) { boolean hidden = "HIDDEN".equals(r.get("moderation_status")); %><tr><td><%=r.get("id")%></td><td><%=HtmlUtil.escapeHtml(r.get("email"))%></td><td><strong><%=HtmlUtil.escapeHtml(r.get("title"))%></strong></td><td><%=HtmlUtil.escapeHtml(r.get("status"))%></td><td><span class="badge <%=hidden ? "badge-banned" : "badge-active"%>"><%=HtmlUtil.escapeHtml(r.get("moderation_status"))%></span></td><td><div class="action-row"><form method="post" action="/admin/content/<%=hidden ? "restore" : "hide"%>"><input type="hidden" name="targetType" value="JOB"><input type="hidden" name="targetId" value="<%=r.get("id")%>"><input type="hidden" name="reason" value="Manual moderation review"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><button class="btn-sm <%=hidden ? "btn-unban" : "btn-ban"%>"><%=hidden ? "Restore" : "Hide"%></button></form><form method="post" action="/admin/content/delete-job"><input type="hidden" name="id" value="<%=r.get("id")%>"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><button class="btn-sm btn-delete" onclick="return confirm('Delete this job?')">Delete</button></form></div></td></tr><% } %>
</tbody></table></div>

<h2 class="section-title">Services · <%=services.size()%></h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>ID</th><th>Owner</th><th>Title</th><th>Visibility</th><th>Moderation actions</th></tr></thead><tbody>
<% for (Map<String,Object> r : services) { boolean hidden = "HIDDEN".equals(r.get("moderation_status")); %><tr><td><%=r.get("id")%></td><td><%=HtmlUtil.escapeHtml(r.get("email"))%></td><td><strong><%=HtmlUtil.escapeHtml(r.get("title"))%></strong></td><td><span class="badge <%=hidden ? "badge-banned" : "badge-active"%>"><%=HtmlUtil.escapeHtml(r.get("moderation_status"))%></span></td><td><div class="action-row"><form method="post" action="/admin/content/<%=hidden ? "restore" : "hide"%>"><input type="hidden" name="targetType" value="SERVICE"><input type="hidden" name="targetId" value="<%=r.get("id")%>"><input type="hidden" name="reason" value="Manual moderation review"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><button class="btn-sm <%=hidden ? "btn-unban" : "btn-ban"%>"><%=hidden ? "Restore" : "Hide"%></button></form><form method="post" action="/admin/content/delete-service"><input type="hidden" name="id" value="<%=r.get("id")%>"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><button class="btn-sm btn-delete" onclick="return confirm('Delete this service?')">Delete</button></form></div></td></tr><% } %>
</tbody></table></div><footer class="mkv-footer">© 2026 MKV Team</footer></main></div><script src="/js/admin-nav.js?v=20260822"></script></body></html>
