<%-- Design direction: calm editorial control room with focused case review and safe staff-aware actions. --%>
<%@ page import="java.util.Map,java.util.List" %>
<%@ page import="com.studentos.util.HtmlUtil" %>
<%@ page import="com.studentos.model.User" %>
<%@ page import="java.net.URLEncoder" %>
<%
List<Map<String,Object>> reports = (List<Map<String,Object>>) request.getAttribute("reports");
String csrfToken = (String) request.getAttribute("csrfToken"); String msg = request.getParameter("msg");
String reportStatus = (String) request.getAttribute("reportStatus"); String reportType = (String) request.getAttribute("reportType"); String reportQuery = (String) request.getAttribute("reportQuery");
int reportPage = request.getAttribute("reportPage") == null ? 1 : (Integer) request.getAttribute("reportPage"); int reportPages = request.getAttribute("reportPages") == null ? 1 : (Integer) request.getAttribute("reportPages");
User staffUser = (User) session.getAttribute("user"); boolean fullAdmin = staffUser != null && "ADMIN".equals(staffUser.getRole());
String pageBase = "?status=" + URLEncoder.encode(reportStatus == null ? "" : reportStatus, "UTF-8") + "&type=" + URLEncoder.encode(reportType == null ? "" : reportType, "UTF-8") + "&q=" + URLEncoder.encode(reportQuery == null ? "" : reportQuery, "UTF-8") + "&page=";
if (reports == null) reports = new java.util.ArrayList<>();
%>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Moderation reports — StudentOS</title><link rel="stylesheet" href="/css/main.css?v=admin-ui-20260822"><link rel="icon" type="image/png" href="/favicon.png"></head>
<body><div class="admin-shell"><aside class="admin-rail"><div class="admin-brand">StudentOS <span><%=fullAdmin ? "Admin" : "Moderator"%></span></div><nav aria-label="Staff navigation"><% if (fullAdmin) { %><a href="/admin">Dashboard</a><a href="/admin/users">Users</a><% } %><a href="/admin/content">Content</a><% if (fullAdmin) { %><a href="/admin/messages">Messages</a><% } %><a href="/admin/reports" class="active">Reports</a><a href="/admin/audit">Audit log</a><a href="/dashboard">Back to App</a></nav><div class="admin-rail-footer"><a href="/auth/logout">Logout</a></div></aside>
<main class="admin-main"><header class="admin-header"><div><p class="eyebrow">Moderation workflow</p><h1>Report review queue</h1><p>Filter active cases, claim review work, and close each report with a clear note.</p></div><div class="admin-header-actions"><span class="admin-status"><%=reports.size()%> cases shown</span><a href="/admin/audit" class="btn btn-secondary">View audit log</a></div></header>
<% if (msg != null) { %><div class="toast">Action completed: <%=HtmlUtil.escapeHtml(msg.replace("_", " "))%></div><% } %>
<form method="get" action="/admin/reports" class="profile-form-card"><div class="profile-field-grid"><div class="form-group"><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-control"><option value="">All statuses</option><option value="OPEN" <%= "OPEN".equals(reportStatus) ? "selected" : "" %>>Open</option><option value="RESOLVED" <%= "RESOLVED".equals(reportStatus) ? "selected" : "" %>>Resolved</option><option value="DISMISSED" <%= "DISMISSED".equals(reportStatus) ? "selected" : "" %>>Dismissed</option></select></div><div class="form-group"><label class="form-label" for="type">Target type</label><select id="type" name="type" class="form-control"><option value="">All types</option><option value="SKILL" <%= "SKILL".equals(reportType) ? "selected" : "" %>>Skill</option><option value="JOB" <%= "JOB".equals(reportType) ? "selected" : "" %>>Job</option><option value="SERVICE" <%= "SERVICE".equals(reportType) ? "selected" : "" %>>Service</option><option value="MESSAGE" <%= "MESSAGE".equals(reportType) ? "selected" : "" %>>Message</option></select></div><div class="form-group"><label class="form-label" for="q">Search</label><input id="q" name="q" class="form-control" maxlength="100" value="<%=HtmlUtil.escapeHtml(reportQuery)%>" placeholder="Reporter, reason, or detail"></div></div><button class="btn btn-primary" type="submit">Apply filters</button> <a class="btn btn-secondary" href="/admin/reports">Clear</a></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Report</th><th>Target</th><th>Reporter</th><th>Reason</th><th>Review state</th><th>Review actions</th></tr></thead><tbody>
<% if (reports.isEmpty()) { %><tr><td colspan="6">No reports match these filters.</td></tr><% } %>
<% for (Map<String,Object> report : reports) { boolean open = "OPEN".equals(report.get("status")); %><tr><td><strong>#<%=report.get("id")%></strong><br><small><%=report.get("created_at")%></small></td><td><strong><%=HtmlUtil.escapeHtml(report.get("target_type"))%> #<%=report.get("target_id")%></strong><br><%=HtmlUtil.escapeHtml(report.get("target_summary"))%><br><small><%=HtmlUtil.escapeHtml(report.get("target_owner_email"))%></small></td><td><%=HtmlUtil.escapeHtml(report.get("reporter_email"))%><% if (report.get("details") != null) { %><br><small><%=HtmlUtil.escapeHtml(report.get("details"))%></small><% } %></td><td><%=HtmlUtil.escapeHtml(report.get("reason"))%></td><td><span class="badge <%=open ? "badge-todo" : "badge-completed"%>"><%=HtmlUtil.escapeHtml(report.get("status"))%></span><br><small>Assigned: <%=HtmlUtil.escapeHtml(report.get("assigned_email"))%></small><% if (report.get("resolution_note") != null) { %><br><small><%=HtmlUtil.escapeHtml(report.get("resolution_note"))%></small><% } %></td><td><% if (open) { %><div class="action-row"><form method="post" action="/admin/reports/assign"><input type="hidden" name="reportId" value="<%=report.get("id")%>"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><button class="btn-sm" type="submit">Assign to me</button></form><% if ("MESSAGE".equals(report.get("target_type"))) { %><form method="post" action="/admin/reports/resolve"><input type="hidden" name="reportId" value="<%=report.get("id")%>"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><input name="reason" maxlength="1000" placeholder="Resolution note" required><button class="btn-sm btn-ban">Resolve</button></form><% } else { %><form method="post" action="/admin/reports/hide"><input type="hidden" name="reportId" value="<%=report.get("id")%>"><input type="hidden" name="targetType" value="<%=HtmlUtil.escapeHtml(report.get("target_type"))%>"><input type="hidden" name="targetId" value="<%=report.get("target_id")%>"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><input name="reason" maxlength="1000" placeholder="Reviewer note" required><button class="btn-sm btn-ban" onclick="return confirm('Hide this content and resolve the report?')">Hide & resolve</button></form><% } %><form method="post" action="/admin/reports/dismiss"><input type="hidden" name="reportId" value="<%=report.get("id")%>"><input type="hidden" name="csrfToken" value="<%=csrfToken%>"><input name="reason" maxlength="1000" placeholder="Dismissal note" required><button class="btn-sm btn-unban">Dismiss</button></form></div><% } else { %><small>Reviewed by <%=HtmlUtil.escapeHtml(report.get("reviewer_email"))%></small><% } %></td></tr><% } %>
</tbody></table></div><div class="page-header-actions"><% if (reportPage > 1) { %><a class="btn btn-secondary" href="/admin/reports<%=pageBase%><%=reportPage - 1%>">Previous</a><% } %><span class="page-subtitle">Page <%=reportPage%> of <%=reportPages%></span><% if (reportPage < reportPages) { %><a class="btn btn-secondary" href="/admin/reports<%=pageBase%><%=reportPage + 1%>">Next</a><% } %></div><footer class="mkv-footer">© 2026 MKV Team</footer></main></div><script src="/js/admin-nav.js?v=20260822"></script></body></html>
